# Generated by Django 5.1.4 on 2025-01-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delisora', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_item',
            new_name='OrderItem',
        ),
    ]
